### ISSUE TITLE
[idea] Introduce worker base image

### ISSUE THREAD

**Issue by msrb** [fabric8-analytics/fabric8-analytics-worker#107]
It takes forever (30-60 minutes) to build our worker image and this makes it hard for example to quickly push fixes to stage/prod environment when needed.

Therefore I propose to create a base image for our worker image which would contain various command line tools that we currently download on each build over and over again.
Worker image would then inherit the tools from the base image and only add actual worker code + dependencies on top of it.

This should speed up the build process quite significantly. However, I am not sure about cons of this approach. Please share your thoughts :)

Thanks.

**Comment by jpopelka** [comment]
That would speed up the tests a lot indeed and I know you've raised this idea couple times already. My thoughts:
* How would the CI work if I changed some part of base image (for example some [hack](https://github.com/fabric8-analytics/fabric8-analytics-worker/tree/master/hack)/install_*.sh script) ?
  Would I need to build the base image locally & push it before opening PR or re-running tests with `[test this]` ?  I guess so, but that situation occurs very rarely and if we document this in Dockerfile.base it shouldn't be such a complication and it's IMHO worth the saved time in other cases.
* I assume that during PR merge Jenkins would first build & push base image and then build & push the actual worker image, right ?

**Comment by msrb** [comment]
Thanks for the comment.

> How would the CI work if I changed some part of base image (for example some hack/install_*.sh script) ?

I think the base image would be a separate project so you'd need to first push changes to the base image and then update the version in worker Dockerfile, e.g.:
```dockerfile
FROM registry.devshift.net/fabric8-analytics/worker-shed:VERSION
```

> I assume that during PR merge Jenkins would first build & push base image and then build & push the actual worker image, right ?

I'd keep those 2 as separate projects in git and Jenkins.
