### ISSUE TITLE
License scans take a looong time

### ISSUE THREAD

**Issue by jpopelka** [fabric8-analytics/fabric8-analytics-worker#137]
Speed up ideas:

- #159 (https://github.com/nexB/scancode-toolkit/issues/689)
- #181 (https://github.com/nexB/scancode-toolkit/issues/712)

**Comment by pombredanne** [comment]
I am game to help.... the goal here has always been to be correct first, fast second... as you pointed out, scanning less is likely the way to go.

**Comment by fridex** [comment]
Still relevant? Both #159 and #181 were merged.

**Comment by jpopelka** [comment]
Let's close it since I don't have any more ideas.

**Comment by pombredanne** [comment]
I am working on optimizations on the ScanCode side and will ping you when ready
