### ISSUE TITLE
Unit test failure: projectatomic/atomic-reactor-https://github.com/projectatomic/atomic-reactor

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-worker#150]
```
tests/workers/test_githuber.py::TestGithuber::test_execute[projectatomic/atomic-reactor-https://github.com/projectatomic/atomic-reactor] FAILED

=================================== FAILURES ===================================
 TestGithuber.test_execute[projectatomic/atomic-reactor-https://github.com/projectatomic/atomic-reactor] 

self = <f8a_worker.conf.F8aConfiguration object at 0x7fd9f83fb550>
item = 'github_token'

    def __getattr__(self, item):
        """
            by default, do what getattr this; in case it fails, look for the configuration
            value in self.entries
            """
        try:
            # original behavior
>           return self.__dict__[item]
E           KeyError: 'github_token'

f8a_worker/conf.py:119: KeyError

During handling of the above exception, another exception occurred:

self = <tests.workers.test_githuber.TestGithuber object at 0x7fd9ed5f2240>
repo_name = 'projectatomic/atomic-reactor'
repo_url = 'https://github.com/projectatomic/atomic-reactor'

    @pytest.mark.parametrize(('repo_name', 'repo_url'), [
        ('projectatomic/atomic-reactor', 'https://github.com/projectatomic/atomic-reactor'),
    ])
    def test_execute(self, repo_name, repo_url):
        task = GithubTask.create_test_instance(repo_name, repo_url)
>       results = task.execute(arguments={})

tests/workers/test_githuber.py:18: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
f8a_worker/workers/githuber.py:102: in execute
    token = self.configuration.github_token
f8a_worker/conf.py:127: in __getattr__
    return self.get(c.path, graceful=c.graceful)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <f8a_worker.conf.F8aConfiguration object at 0x7fd9f83fb550>
path = ['github', 'token'], graceful = True

    def get(self, path, graceful=True):
        """
            get value from merged configuration
    
            :param path: list of str, path within configuration
            :param graceful: bool, fail if the value doesn't exist?
            :return: value it found or None
            """
        node = self.data
        for p in path:
            try:
>               node = node[p]
E               TypeError: 'NoneType' object is not subscriptable

f8a_worker/conf.py:151: TypeError

```

**Comment by tisnik** [comment]
@msrb assigning to you (sorry :-p) because the short git history does not contain info about the original author

**Comment by jpopelka** [comment]
I'm the original author, will take a look.

**Comment by tisnik** [comment]
Thanks a lot @jpopelka

**Comment by jpopelka** [comment]
Do you see this every time ? How do you run the tests ?

**Comment by tisnik** [comment]
I usually fetch newest sources and run ./runtest.sh. And yes, now it fails with every run.

**Comment by jpopelka** [comment]
I tried to update everything and run the tests with `REBUILD=1 ./runtest.sh`, but don't see such problem.

From the log it looks like it's not `TestGithuber` specific problem - the `F8aConfiguration` is empty (its `data` attribute is `None`), which is really strange and I don't have idea how/why that happened.

I can only suggest to rebuild the worker image `cd fabric8-analytics-common; ./docker-compose.sh build worker-ingestion` and the tests and try again `cd fabric8-analytics-worker; REBUILD=1 ./runtest.sh`

**Comment by jpopelka** [comment]
We also [volume mount](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/runtest.sh#L95) the `f8a_worker/` directory into the container where we run tests.
So my another idea is that you perhaps did some unintentional change in `f8a_worker/` which is now propagated into the tests every time you run them ?

**Comment by tisnik** [comment]
Thanks @jpopelka , let's check that ;)

**Comment by tisnik** [comment]
Well I must confess it is very strange, but the problem persists here. I'd need to look what's different on my side...

**Comment by jpopelka** [comment]
The only other idea is that perhaps you installed the dependencies locally with `pip` instead of `pip3` (as mentioned in https://github.com/fabric8-analytics/fabric8-analytics-common/pull/130

But I doubt this could influence the tests running in container.

**Comment by jpopelka** [comment]
Are you still seeing this issue ?

**Comment by jpopelka** [comment]
Closing, haven't heard about it from @tisnik since then.
