### ISSUE TITLE
Get rid of env.sh hack

### ISSUE THREAD

**Issue by fridex** [fabric8-analytics/fabric8-analytics-worker#188]
Environment hack present in worker is not nice - it renames some variables which makes it confusing to do addition configuration changes. As we configure env variables directly in docker-compose.yaml or OpenShift templates, we should remove this dirty hack and rather directly configure environment from YAML configs/templates.

https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/hack/env.sh

**Comment by jpopelka** [comment]
Moved to https://github.com/openshiftio/openshift.io/issues/949, closing
