### ISSUE TITLE
need to component_summary in extract_component_details() method

### ISSUE THREAD

**Issue by SaketJNU** [fabric8-analytics/fabric8-analytics-worker#192]
Hi,

As integration_test related to sentiment analysis has included a new variable "magnitude" in "sentiment" data. The same is required to include in "component_summary" of "extract_component_details()" in "stackaggregator_v2.py".   and default values are also incorrect. 

Otherwise, it may results in failure of  integration test for sentiment. 

Thanks,
Saket

**Comment by msrb** [comment]
Related PR: https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/193

**Comment by SaketJNU** [comment]
yes, a PR https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/193 is opened to fix this issue.

**Comment by msrb** [comment]
Yeah, I just wanted to link the issue with the PR so when people come here later, in future, it will be obvious how this issue was fixed :)

**Comment by fridex** [comment]
Based on PR, this issue should be fixed. Closing, but feel free to reopen if this issue persists.
