### ISSUE TITLE
[ERROR] f8a_worker.process: unable to download: http://repo1.maven.org/maven2/<artifact>.jar

### ISSUE THREAD

**Issue by jpopelka** [fabric8-analytics/fabric8-analytics-worker#225]
examples:

- [INFO] f8a_worker.process: downloading maven package org.netbeans.api:org-netbeans-modules-java-source:RELEASE81
[ERROR] f8a_worker.process: unable to download: http://repo1.maven.org/maven2/org/netbeans/api/org-netbeans-modules-java-source/RELEASE81/org-netbeans-modules-java-source-RELEASE81.jar

- [INFO] f8a_worker.process: downloading maven package org.huangpu:mydog-core:1.0-SNAPSHOT
[ERROR] f8a_worker.process: unable to download: http://repo1.maven.org/maven2/org/huangpu/mydog-core/1.0-SNAPSHOT/mydog-core-1.0-SNAPSHOT.jar

- [INFO] f8a_worker.process: downloading maven package org.springframework.boot:spring-boot-starter-thymeleaf:1.3.0.M2
[ERROR] f8a_worker.process: unable to download: http://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-thymeleaf/1.3.0.M2/spring-boot-starter-thymeleaf-1.3.0.M2.jar

- [INFO] f8a_worker.process: downloading maven package org.netbeans.api:org-openide-util:RELEASE81
[ERROR] f8a_worker.process: unable to download: http://repo1.maven.org/maven2/org/netbeans/api/org-openide-util/RELEASE81/org-openide-util-RELEASE81.jar

- [INFO] f8a_worker.process: downloading maven package com.example:dubbo-service-api:1.0-SNAPSHOT
[ERROR] f8a_worker.process: unable to download: http://repo1.maven.org/maven2/com/example/dubbo-service-api/1.0-SNAPSHOT/dubbo-service-api-1.0-SNAPSHOT.jar

- [INFO] f8a_worker.process: downloading maven package io.springcat:GlobalDef:0.0.1-SNAPSHOT
[ERROR] f8a_worker.process: unable to download: http://repo1.maven.org/maven2/io/springcat/GlobalDef/0.0.1-SNAPSHOT/GlobalDef-0.0.1-SNAPSHOT.jar

**Comment by jpopelka** [comment]
http://mvnrepository.com does not know

- org.huangpu:mydog-core:1.0-SNAPSHOT
- com.example:dubbo-service-api:1.0-SNAPSHOT
- io.springcat:GlobalDef:0.0.1-SNAPSHOT

Others should be fixed with #226

**Comment by msrb** [comment]
There is more Maven repositories out there, even Red Hat has one https://maven.repository.redhat.com/ga/

We only support the main one for each ecosystem at the moment, i.e. Maven Central for Maven.

Since the list of dependencies was taken from manifest files found on GitHub, it's not surprising that it's full of crappy and non-existent packages :)
