### ISSUE TITLE
declared license in nuget metadata is URL

### ISSUE THREAD

**Issue by jpopelka** [fabric8-analytics/fabric8-analytics-worker#237]
From [.nuspec reference](https://docs.microsoft.com/en-us/nuget/schema/nuspec#optional-metadata-elements):
`licenseUrl`:  A URL for the package's license, often shown in UI displays as well as nuget.org.

We probably need to download the file that the `licenseUrl` points to and run scancode (the tool we use in license scanner) on it.

**Comment by msrb** [comment]
+1 very good catch.
