### ISSUE TITLE
Move Graph Importer as part of Selinon Workers

### ISSUE THREAD

**Issue by miteshvp** [fabric8-analytics/fabric8-analytics-worker#263]
Currently, graph sync for any EPV happens outside of worker process by way of data-model's API endpoint. This unnecessarily increases a moving piece and one more disconnected data gathering. Rather we should move this graph importer task as part of other selinon stable, so that we can take advantage of audit trail and sync to graph only those EPVs that are either failed/refreshed.

**Comment by msrb** [comment]
This issue was moved to openshiftio/openshift.io#688
