### ISSUE TITLE
Cleanup old data from the S3 bayesian-core-data bucket

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-worker#339]
The following package metadata: ```github_details.json``` and ```keywords_tagging.json``` are now stored in: ```bayesian-core-data``` bucket, not in the ```bayesian-core-package-data``` bucket. Is it possible to cleanup the old metadata that are not going to be used anymore?

**Comment by fridex** [comment]
This affects only `github_details.json`. We perform keywords tagging on package level and package-version level as well. So `keywords_tagging.json` files are correctly present in both buckets, do not delete them.

**Comment by tisnik** [comment]
I see, thank you. Is this quite new feature, right? Because I don't see this analysis for all components...

**Comment by jpopelka** [comment]
Moved to https://github.com/openshiftio/openshift.io/issues/2149
