### ISSUE TITLE
[githuber] worker depends on GitHub's Search API which has limit 30 requests/minute for authenticated users

### ISSUE THREAD

**Issue by msrb** [fabric8-analytics/fabric8-analytics-worker#90]
In `_issues_or_prs_count(self, gh, query)` we call `gh.search_issues(query=query)` which uses GitHub's Search API. This API has [a custom rate limit](https://developer.github.com/v3/search/#rate-limit) 30 requests per minute.

No wonder we are getting 403 so often.

```
    {
      "rate": {
        "limit": 5000,
        "remaining": 4992,
        "reset": 1499694994
      },
      "resources": {
        "core": {
          "limit": 5000,
          "remaining": 4992,
          "reset": 1499694994
        },
        "graphql": {
          "limit": 5000,
          "remaining": 5000,
          "reset": 1499697453
        },
        "search": {
          "limit": 30,
          "remaining": 22,
          "reset": 1499693874
        }
      }
```

**Comment by miteshvp** [comment]
Yes, that's correct. Previously it was implemented using pagination and for data was gathered for last two weeks. So it was much easier to paginate and get total count. After that, the use-case identified was to fetch last month and last year's data corresponding to issues/prs, which was taking close to 4 minutes to get the total count. Hence it was decided to use /search api which reduced the response time to around 18 seconds, but con is rate-limiting.

**Comment by msrb** [comment]
@miteshvp Using /search API in workers is no-go as it will never work with higher number of workers. We will immediately hit the limit. Especially when it takes 8 /search API calls to get the data for a single package. I don't remember seeing this data used anywhere, is the use-case still valid?

**Comment by miteshvp** [comment]
> is the use-case still valid?
unfortunately no since, we do not show this data anywhere. 
> We will immediately hit the limit
We should use more tokens if the use-case is still valid. Else, I will be ok to stop collecting this data. Any thoughts?

**Comment by fridex** [comment]
> We should use more tokens if the use-case is still valid. Else, I will be ok to stop collecting this data. Any thoughts?

I would consider these data really valuable for analytics algorithms. We can talk about it.

**Comment by msrb** [comment]
> We should use more tokens if the use-case is still valid.

The problem is that the rate limit on Search API is so low that we would need a huge number of tokens.

I'd propose to stop collecting the data the way we are collecting them now and look for other ways of collecting them, if we consider the data valuable.

**Comment by jpopelka** [comment]
> I'd propose to stop collecting the data the way we are collecting them now and look for other ways of collecting them

I was looking at the new [v4 API](https://developer.github.com/v4/) few weeks ago in #80 and while it looks promising there are still some features (that we need) missing at the moment.

**Comment by msrb** [comment]
Fixed, closing.
